
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyd-project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cyd-project
  template:
    metadata:
      labels:
        app: cyd-project
    spec:
      containers:
        - name: cyd
          image: gache001/cyd_project:v1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"

---
apiVersion: v1
kind: Service
metadata:
  name: cyd-project
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: cyd-project
